"""
Report Generator — Generates downloadable Difficulty Justification Reports.
"""
import streamlit as st
from datetime import datetime


def generate_report(result: dict) -> str:
    """Generate a markdown report from the analysis results."""
    ml_stats = result.get("ml_stats", {})
    feature_audit = result.get("feature_audit", [])
    reasoning = result.get("reasoning", "")
    refined = result.get("refined_questions", {})
    validation = result.get("validation_results", {})
    justification = result.get("difficulty_justification", "")
    bloom_level = result.get("current_bloom_level", "Unknown")
    
    report = f"""# EduAgent-OS — Assessment Analysis Report
**Generated**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

---

## 1. Original Question
```
{result.get('raw_question', 'N/A')}
```

## 2. ML Analysis Summary

| Metric | Value |
|--------|-------|
| **Difficulty** | {ml_stats.get('difficulty', 'N/A')} |
| **Difficulty Index** | {ml_stats.get('difficulty_index', 'N/A')} |
| **Discrimination** | {ml_stats.get('discrimination', 'N/A')} |
| **Discrimination Index** | {ml_stats.get('discrimination_index', 'N/A')} |
| **Confidence** | {ml_stats.get('confidence', 'N/A')} |
| **Bloom's Level** | {bloom_level} |

### Feature Importance
"""
    
    importance = ml_stats.get("feature_importance", {})
    for name, val in list(importance.items())[:8]:
        report += f"- **{name}**: {val:.1%}\n"
    
    report += "\n### Quality Audit\n"
    if feature_audit:
        for flag in feature_audit:
            report += f"- {flag}\n"
    else:
        report += "- ✅ No issues detected\n"
    
    report += f"""
## 3. Expert Reasoning

{reasoning}

## 4. Refined Versions

### Difficulty Justification
{justification}

"""
    
    for level in ["easy", "medium", "hard"]:
        question = refined.get(level, "")
        val = validation.get(level, {})
        if question:
            predicted = val.get("predicted_difficulty", "?")
            matches = "✅" if val.get("matches", False) else "⚠️"
            
            report += f"""### {level.upper()} Version {matches}
- Predicted Difficulty: {predicted}
- Difficulty Index: {val.get('difficulty_index', 'N/A')}

{question}

---

"""
    
    report += """
## 5. Methodology
- **ML Models**: XGBoost classifiers (Model A: text features, Model B: all features)
- **Knowledge Base**: FAISS-indexed pedagogical research (Bloom's Taxonomy, IRT, MCQ design)
- **LLM**: Groq API (Llama 3.1 70B)
- **Framework**: LangGraph state machine with iterative refinement

---
*Report generated by EduAgent-OS — The Autonomous Assessment Optimizer*
"""
    
    return report


def render_report_download(result: dict):
    """Render the report download button."""
    if not result.get("ml_stats"):
        return
    
    report = generate_report(result)
    
    st.download_button(
        label="📄 Download Full Report",
        data=report,
        file_name=f"eduagent_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md",
        mime="text/markdown",
        use_container_width=True
    )
